version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: my_node_app
    env_file:
      - .env  
    environment:
      DATABASE_URL: postgres://postgres_user:postgres_password@db:5432/my_database
      PORT: 8080
    depends_on:
      - db
    ports:
      - "8080:8080"

  db:
    image: postgres:13  
    container_name: my_postgres_db 
    environment:
      POSTGRES_USER: postgres_user   
      POSTGRES_PASSWORD: postgres_password  
      POSTGRES_DB: my_database  
    ports:
      - "5432:5432"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: my_next_app
    env_file:
      - .env
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8080
    depends_on:
      - backend
    ports:
      - "80:80"

